DOMAIN = "jfl_active"
MANUFACTURER ="JFL"
CONF_ALT_NIGHT_MODE = "alt_night_mode"
CONF_CODE_REQUIRED = "code_required"
CONF_AUTO_BYPASS = "auto_bypass"
CONF_CODE_ARM_REQUIRED = "code_arm_required"
CONF_HOST = "host"
CONF_PORT = "port"
CONF_CODE_REQUIRED = "code_required"
CONF_CODE_ARM_REQUIRED = "code_arm_required"
DEFAULT_ALT_NIGHT_MODE = False
DEFAULT_AUTO_BYPASS = False
DEFAULT_CODE_ARM_REQUIRED = True
DEFAULT_CODE_REQUIRED = "0000"
DEFAULT_DEVICE_PORT = 8085
DEFAULT_DEVICE_HOST = "localhost"
DEFAULT_ARM_OPTIONS = {
    CONF_ALT_NIGHT_MODE: DEFAULT_ALT_NIGHT_MODE,
    CONF_AUTO_BYPASS: DEFAULT_AUTO_BYPASS,
    CONF_CODE_ARM_REQUIRED: DEFAULT_CODE_ARM_REQUIRED,
    CONF_CODE_REQUIRED: DEFAULT_CODE_REQUIRED,
}

OPTIONS_ARM = "arm_options"
SIGNAL_PANEL_MESSAGE = "jfl_active.panel_message"
SIGNAL_REL_MESSAGE = "jfl_active.rel_message"
SIGNAL_RFX_MESSAGE = "jfl_active.rfx_message"
SIGNAL_ZONE_FAULT = "jfl_active.zone_fault"
SIGNAL_ZONE_RESTORE = "jfl_active.zone_restore"
