alarm_command:
  name: envia comando de arme e desarme para as particoes
  description: envia comando de arme e desarme para as particoes
  target:
    entity:
      integration: jfl_active
      domain: alarm_control_panel
  fields:
    code:
      name: code
      description: O codigo de arme  / desarme.
      required: true
      example: 1234
      selector:
        text:
    particao:
      name: particao
      description: o numero da particao
      required: true
      exemple: 4
      selector:
        text:
